# General Configs
[__config]
base_url = "https://dummyjson.com" 
bearer_token = ""

# A table defines a new fetch action, response will save to {table name}.json
# This fetches /products/search?q=Laptop and save response to `laptops.json`
[laptops]
endpoint = "/products/search"
query = { q = 'Laptop' }

# This fetches /products and save response to `products.json`
[products]