[__config]
base_url = "https://dummyjson.com" 
bearer_token = ""


# A table defines a new fetch action, this tag name is the filename where response will save to
[laptops]
endpoint = "/products/search"
query = { q = 'Laptop' }

# This fetches /products endpoint with no query
[products]