version: "3.7"

services:
    json-puller:
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        environment:
          - OUTPUT_DIR=./data
          - USE_REMOTE_CONFIG=0
          - CONFIG_RELOAD=1
          - CONFIG_FILE_PATH=./config.toml
        volumes:
          - ./data:/data
          - ./config.toml:/config.toml